(()=>{
'use strict';
let mode=null,library=[],vaultRows=[],vaultItems=[],vaultKey=null,vaultProfile=null,lockTimer=null,revealTimers=new Map();
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const ctx=()=>window.FocusModulesContext?.()||{};
const uid=()=>ctx().user?.id;
function toast(s){const n=document.createElement('div');n.className='module-toast';n.textContent=s;document.body.append(n);setTimeout(()=>n.remove(),2200)}
function needAuth(){if(!ctx().client||!uid()){renderMessage('Войдите в Focus','Библиотека и доступы синхронизируются через ваш аккаунт.');return true}return false}
function renderMessage(title,text){$('#board').innerHTML=`<div class="module-shell"><div class="module-empty"><h3>${esc(title)}</h3><p>${esc(text)}</p></div></div>`}
function setMode(next){mode=next;document.body.classList.toggle('module-mode',!!mode);document.querySelectorAll('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.module===mode));if(mode)render();}
document.querySelectorAll('[data-module]').forEach(b=>b.addEventListener('click',()=>setMode(b.dataset.module)));
document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>{mode=null;document.body.classList.remove('module-mode');$('.topbar h1').textContent=b.dataset.view==='done'?'Выполненные':b.dataset.view==='inbox'?'Входящие':'Задачи';document.querySelectorAll('[data-module]').forEach(x=>x.classList.remove('active'));setTimeout(()=>window.render?.(),0)}));
async function render(){if(!mode)return;const requested=mode;if(needAuth())return;$('.topbar h1').textContent=mode==='library'?'Библиотека':'Доступы';$('#board').innerHTML='<div class="module-shell"><div class="module-empty"><h3>Загружаем…</h3></div></div>';if(mode==='library')await loadLibrary(requested);else await loadVault(requested);}

async function loadLibrary(requested='library'){const{data,error}=await ctx().client.from('library_items').select('*').is('deleted_at',null).order('is_favorite',{ascending:false}).order('updated_at',{ascending:false});if(mode!==requested)return;if(error)return dbError(error);library=data||[];$('#libraryCount').textContent=library.length;renderLibrary()}
function renderLibrary(q=''){const term=q.trim().toLowerCase(),rows=library.filter(x=>!term||[x.title,x.description,x.content,x.language,(x.tags||[]).join(' ')].join(' ').toLowerCase().includes(term));$('#board').innerHTML=`<div class="module-shell"><div class="module-hero"><div><div class="module-kicker">CodeBridge внутри Focus</div><h2>Библиотека решений</h2><p>Код, формулы Excel, SQL и рабочие заготовки — рядом с задачами.</p></div><div class="module-actions"><input class="module-input module-search" id="libSearch" placeholder="Найти код, тег или формулу"><button class="module-button" id="libImport">Импорт JSON</button><button class="module-button primary" id="libNew">＋ Добавить</button><input type="file" id="libFile" accept="application/json,.json" hidden></div></div><div class="module-grid" id="libGrid">${rows.length?rows.map(libraryCard).join(''):`<div class="module-empty"><h3>Библиотека пока пуста</h3><p>Добавьте первую формулу, макрос или SQL-запрос.</p></div>`}</div></div>`;$('#libSearch').value=q;$('#libSearch').oninput=e=>renderLibrary(e.target.value);$('#libNew').onclick=()=>libraryDialog();$('#libImport').onclick=()=>$('#libFile').click();$('#libFile').onchange=e=>previewLibraryImport(e.target.files[0]);$('#libGrid').onclick=libraryAction}
function libraryCard(x){return `<article class="module-card" data-id="${x.id}"><div class="module-card-top"><span class="module-badge">${esc(x.language)}</span><button class="star ${x.is_favorite?'on':''}" data-act="star" title="Избранное">★</button></div><h3>${esc(x.title)}</h3><p>${esc(x.description||'Без описания')}</p><pre class="module-code">${esc(x.content)}</pre><div class="module-card-foot"><button data-act="copy">Копировать</button><button data-act="edit">Изменить</button></div></article>`}
async function libraryAction(e){const b=e.target.closest('button'),card=e.target.closest('[data-id]');if(!b||!card)return;const item=library.find(x=>x.id===card.dataset.id);if(b.dataset.act==='copy'){await navigator.clipboard.writeText(item.content);toast('Скопировано')}if(b.dataset.act==='edit')libraryDialog(item);if(b.dataset.act==='star'){await ctx().client.from('library_items').update({is_favorite:!item.is_favorite}).eq('id',item.id);loadLibrary()}}
function libraryDialog(item={}){dialog(`
<h2>${item.id?'Изменить':'Новая'} запись</h2><form class="module-form" id="moduleForm">
<label>Название<input name="title" required maxlength="160" value="${esc(item.title||'')}"></label><div class="module-form-row"><label>Тип<select name="language">${['excel','vba','sql','python','javascript','text'].map(x=>`<option ${item.language===x?'selected':''}>${x}</option>`).join('')}</select></label><label>Теги<input name="tags" value="${esc((item.tags||[]).join(', '))}" placeholder="excel, отчёт"></label></div><label>Описание<input name="description" value="${esc(item.description||'')}"></label><label>Код или формула<textarea name="content" required>${esc(item.content||'')}</textarea></label><div class="module-dialog-actions">${item.id?'<button type="button" class="module-button" id="moduleDelete">Удалить</button>':''}<button type="button" class="module-button" data-close>Отмена</button><button class="module-button primary">Сохранить</button></div></form>`);$('#moduleForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),row={user_id:uid(),title:f.get('title').trim(),language:f.get('language'),description:f.get('description').trim(),content:f.get('content'),tags:f.get('tags').split(',').map(x=>x.trim()).filter(Boolean)};const q=item.id?ctx().client.from('library_items').update(row).eq('id',item.id):ctx().client.from('library_items').insert(row);const{error}=await q;if(error)return formError(error.message);closeDialog();loadLibrary()};$('#moduleDelete')?.addEventListener('click',async()=>{await ctx().client.from('library_items').update({deleted_at:new Date().toISOString()}).eq('id',item.id);closeDialog();loadLibrary()})}

function canonicalLibrary(x){const norm=s=>String(s??'').normalize('NFC').replace(/\r\n?/g,'\n').trim();return `${norm(x.title).toLowerCase().replace(/\s+/g,' ')}\0${norm(x.language).toLowerCase()}\0${norm(x.content)}`}
async function previewLibraryImport(file){if(!file)return;try{const raw=JSON.parse(await file.text());if(!Array.isArray(raw))throw Error('В файле должен быть массив карточек CodeBridge');const allowed=new Set(['vba','excel','javascript','python','sql','html','css','json','powershell','batch','text','other']),known=new Set(library.map(canonicalLibrary)),seen=new Set(),fresh=[];let duplicates=0,invalid=0;raw.forEach((r,i)=>{if(!r||typeof r!=='object'){invalid++;return}const language=String(r.language||'text').toLowerCase(),row={user_id:uid(),title:String(r.title||'Без названия').trim().slice(0,160)||'Без названия',description:String(r.description||''),content:String(r.code??r.content??''),language:allowed.has(language)?language:'other',tags:Array.isArray(r.tags)?[...new Set(r.tags.map(x=>String(x).trim()).filter(Boolean))].slice(0,50):[],project_label:'CodeBridge',link_url:'',image_paths:[],is_favorite:Boolean(r.is_favorite),sort_order:i};const key=canonicalLibrary(row);if(known.has(key)||seen.has(key)){duplicates++;return}seen.add(key);fresh.push(row)});dialog(`<h2>Импорт из CodeBridge</h2><div class="import-summary"><div><strong>${fresh.length}</strong><span>новых</span></div><div><strong>${duplicates}</strong><span>дублей</span></div><div><strong>${invalid}</strong><span>ошибок</span></div></div><p class="module-note">Дубли будут пропущены. Изображения из старого хранилища не переносятся автоматически.</p><div id="moduleError"></div><div class="module-dialog-actions"><button class="module-button" data-close>Отмена</button><button class="module-button primary" id="confirmImport" ${fresh.length?'':'disabled'}>Импортировать</button></div>`);$('#confirmImport').onclick=()=>importLibraryRows(fresh)}catch(e){toast(`Не удалось прочитать файл: ${e.message}`)}}
async function importLibraryRows(rows){const button=$('#confirmImport');button.disabled=true;button.textContent='Импортируем…';const{error}=await ctx().client.from('library_items').insert(rows);if(error){button.disabled=false;button.textContent='Повторить';return formError(error.message)}closeDialog();toast(`Добавлено карточек: ${rows.length}`);loadLibrary()}

const enc=new TextEncoder(),dec=new TextDecoder(),b64=a=>{let s='';for(const n of a)s+=String.fromCharCode(n);return btoa(s)},unb64=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
async function derive(password,salt,it){const m=await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',salt,iterations:it,hash:'SHA-256'},m,{name:'AES-GCM',length:256},false,['encrypt','decrypt'])}
async function crypt(key,bytes,aad){const iv=crypto.getRandomValues(new Uint8Array(12)),cipher=await crypto.subtle.encrypt({name:'AES-GCM',iv,additionalData:enc.encode(aad)},key,bytes);return{iv:b64(iv),ciphertext:b64(new Uint8Array(cipher))}}
async function decrypt(key,e,aad){return new Uint8Array(await crypto.subtle.decrypt({name:'AES-GCM',iv:unb64(e.iv),additionalData:enc.encode(aad)},key,unb64(e.ciphertext)))}
async function loadVault(requested='vault'){const{data,error}=await ctx().client.from('vault_profiles').select('*').eq('user_id',uid()).maybeSingle();if(mode!==requested)return;if(error)return dbError(error);vaultProfile=data;if(!vaultProfile)return renderVaultGate('create');if(!vaultKey)return renderVaultGate('unlock');await loadVaultItems()}
function renderVaultGate(kind){$('#board').innerHTML=`<div class="module-shell"><div class="module-hero"><div><div class="module-kicker">Зашифровано на устройстве</div><h2>Доступы</h2><p>Логины и пароли синхронизируются, но расшифровываются только в вашем браузере.</p></div></div><div class="vault-gate"><h3>${kind==='create'?'Создайте защищённое хранилище':'Хранилище заблокировано'}</h3><p>${kind==='create'?'Придумайте отдельный мастер-пароль не короче 12 символов. Восстановить его невозможно.':'Введите мастер-пароль. Он не отправляется в Focus или Supabase.'}</p><button class="module-button primary" id="vaultGate">${kind==='create'?'Создать хранилище':'Разблокировать'}</button></div></div>`;$('#vaultGate').onclick=()=>vaultPasswordDialog(kind)}
function vaultPasswordDialog(kind){dialog(`<h2>${kind==='create'?'Новый мастер-пароль':'Разблокировка'}</h2><form class="module-form" id="moduleForm"><label>Мастер-пароль<input type="password" autocomplete="current-password" name="password" required></label>${kind==='create'?'<label>Повторите пароль<input type="password" autocomplete="new-password" name="confirm" required></label>':''}<div id="moduleError"></div><div class="module-dialog-actions"><button type="button" class="module-button" data-close>Отмена</button><button class="module-button primary">Продолжить</button></div></form>`);$('#moduleForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),p=f.get('password');if(p.length<12)return formError('Минимум 12 символов');if(kind==='create'&&p!==f.get('confirm'))return formError('Пароли не совпадают');e.submitter.disabled=true;kind==='create'?await createVault(p):await unlockVault(p)}}
async function createVault(password){try{const salt=crypto.getRandomValues(new Uint8Array(16)),iterations=600000,kek=await derive(password,salt,iterations),raw=crypto.getRandomValues(new Uint8Array(32)),wrapped=await crypt(kek,raw,`focus:vault-key:v1:${uid()}`),key=await crypto.subtle.importKey('raw',raw,{name:'AES-GCM'},false,['encrypt','decrypt']);raw.fill(0);const verifier=await crypt(key,enc.encode('FOCUS_VAULT_VERIFIER_V1'),`focus:vault-verifier:v1:${uid()}`),row={user_id:uid(),version:1,kdf:{name:'PBKDF2',hash:'SHA-256',iterations,salt:b64(salt)},wrapped_key:wrapped,verifier};const{error}=await ctx().client.from('vault_profiles').insert(row);if(error)throw error;vaultProfile=row;vaultKey=key;closeDialog();armLock();loadVaultItems()}catch(e){formError(e.message)}}
async function unlockVault(password){try{const k=vaultProfile.kdf,kek=await derive(password,unb64(k.salt),k.iterations),raw=await decrypt(kek,vaultProfile.wrapped_key,`focus:vault-key:v1:${uid()}`),candidate=await crypto.subtle.importKey('raw',raw,{name:'AES-GCM'},false,['encrypt','decrypt']);raw.fill(0);const proof=dec.decode(await decrypt(candidate,vaultProfile.verifier,`focus:vault-verifier:v1:${uid()}`));if(proof!=='FOCUS_VAULT_VERIFIER_V1')throw Error();vaultKey=candidate;closeDialog();armLock();loadVaultItems()}catch{formError('Неверный мастер-пароль')}}
function armLock(){clearTimeout(lockTimer);lockTimer=setTimeout(lockVault,5*60*1000)}function lockVault(){vaultKey=null;vaultItems=[];revealTimers.forEach(clearTimeout);revealTimers.clear();closeDialog();if(mode==='vault')renderVaultGate('unlock')}
async function loadVaultItems(){const owner=uid();const{data,error}=await ctx().client.from('vault_items').select('*').is('deleted_at',null).order('updated_at',{ascending:false});if(mode!=='vault'||uid()!==owner||!vaultKey)return;if(error)return dbError(error);vaultRows=data||[];vaultItems=[];let bad=0;for(const row of vaultRows)try{vaultItems.push({...JSON.parse(dec.decode(await decrypt(vaultKey,row.envelope,`focus:vault-item:v1:${owner}:${row.id}`))),id:row.id})}catch{bad++}if(mode==='vault'&&uid()===owner&&vaultKey)renderVault(bad)}
function renderVault(bad=0){$('#board').innerHTML=`<div class="module-shell"><div class="module-hero"><div><div class="module-kicker">Локальное расшифрование · AES-GCM</div><h2>Доступы</h2><p>Быстро копируйте логин или пароль. Секреты не участвуют в общем поиске.</p></div><div class="module-actions"><input class="module-input module-search" id="vaultSearch" placeholder="Найти сервис"><button class="module-button primary" id="vaultNew">＋ Добавить</button></div></div><div class="vault-toolbar"><span class="vault-health">● Хранилище разблокировано</span><button class="module-button" id="vaultLock">Заблокировать</button></div>${bad?`<div class="module-error">Не удалось расшифровать записей: ${bad}</div>`:''}<div class="module-grid" id="vaultGrid"></div></div>`;drawVault();$('#vaultSearch').oninput=drawVault;$('#vaultNew').onclick=()=>vaultItemDialog();$('#vaultLock').onclick=lockVault;$('#vaultGrid').onclick=vaultAction;armLock()}
function drawVault(){const term=($('#vaultSearch')?.value||'').toLowerCase(),items=vaultItems.filter(x=>!term||[x.title,x.username,x.category,(x.tags||[]).join(' ')].join(' ').toLowerCase().includes(term));$('#vaultGrid').innerHTML=items.length?items.map(x=>`<article class="module-card" data-id="${x.id}"><div class="module-card-top"><span class="module-badge">${esc(x.category||'Без категории')}</span><button class="star ${x.favorite?'on':''}" data-act="edit">•••</button></div><h3>${esc(x.title)}</h3><div class="vault-secret"><span>${esc(x.username||'Логин не указан')}</span><button data-act="login">Копировать</button></div><div class="vault-secret masked"><span data-password>••••••••••••</span><button data-act="reveal">Показать</button><button data-act="password">Копировать</button></div><div class="module-card-foot">${x.url?'<button data-act="open">Открыть сайт</button>':''}<button data-act="edit">Изменить</button></div></article>`).join(''):'<div class="module-empty"><h3>Нет карточек</h3><p>Добавьте первый доступ.</p></div>'}
async function vaultAction(e){armLock();const b=e.target.closest('button'),card=e.target.closest('[data-id]');if(!b||!card)return;const x=vaultItems.find(v=>v.id===card.dataset.id);if(b.dataset.act==='login'){await copySecret(x.username,'Логин скопирован')}if(b.dataset.act==='password'){await copySecret(x.password,'Пароль скопирован')}if(b.dataset.act==='open'){try{const u=new URL(x.url);if(!['http:','https:'].includes(u.protocol))throw Error();window.open(u.href,'_blank','noopener')}catch{toast('Ссылка должна начинаться с http:// или https://')}}if(b.dataset.act==='edit')vaultItemDialog(x);if(b.dataset.act==='reveal'){const span=card.querySelector('[data-password]');span.textContent=x.password;b.textContent='Скрыть';clearTimeout(revealTimers.get(x.id));revealTimers.set(x.id,setTimeout(()=>{span.textContent='••••••••••••';b.textContent='Показать'},12000))}}
async function copySecret(value,msg){await navigator.clipboard.writeText(value||'');toast(msg);setTimeout(async()=>{try{if(await navigator.clipboard.readText()===value)await navigator.clipboard.writeText('')}catch{}},45000)}
function vaultItemDialog(item={}){dialog(`<h2>${item.id?'Изменить':'Новый'} доступ</h2><form class="module-form" id="moduleForm"><label>Сервис<input name="title" required value="${esc(item.title||'')}"></label><div class="module-form-row"><label>Логин<input name="username" value="${esc(item.username||'')}"></label><label>Пароль<input name="password" autocomplete="new-password" value="${esc(item.password||'')}"></label></div><div class="module-form-row"><label>Ссылка<input name="url" type="url" value="${esc(item.url||'')}"></label><label>Категория<input name="category" value="${esc(item.category||'Работа')}"></label></div><label>Теги<input name="tags" value="${esc((item.tags||[]).join(', '))}"></label><label>Комментарий<textarea name="notes">${esc(item.notes||'')}</textarea></label><div id="moduleError"></div><div class="module-dialog-actions">${item.id?'<button type="button" class="module-button" id="moduleDelete">Удалить</button>':''}<button type="button" class="module-button" data-close>Отмена</button><button class="module-button primary">Сохранить</button></div></form>`);$('#moduleForm').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),id=item.id||crypto.randomUUID(),now=new Date().toISOString(),plain={schema:1,title:f.get('title').trim(),username:f.get('username'),password:f.get('password'),url:f.get('url'),category:f.get('category'),tags:f.get('tags').split(',').map(x=>x.trim()).filter(Boolean),notes:f.get('notes'),favorite:item.favorite||false,createdAt:item.createdAt||now,updatedAt:now},envelope=await crypt(vaultKey,enc.encode(JSON.stringify(plain)),`focus:vault-item:v1:${uid()}:${id}`),row={id,user_id:uid(),version:1,envelope};const q=item.id?ctx().client.from('vault_items').update({envelope}).eq('id',id):ctx().client.from('vault_items').insert(row);const{error}=await q;if(error)return formError(error.message);closeDialog();loadVaultItems()};$('#moduleDelete')?.addEventListener('click',async()=>{await ctx().client.from('vault_items').update({deleted_at:new Date().toISOString()}).eq('id',item.id);closeDialog();loadVaultItems()})}
function dialog(html){const o=document.createElement('div');o.className='module-overlay';o.id='moduleOverlay';o.innerHTML=`<section class="module-dialog">${html}</section>`;document.body.append(o);o.onclick=e=>{if(e.target===o||e.target.closest('[data-close]'))closeDialog()}}
function closeDialog(){$('#moduleOverlay')?.remove()}function formError(s){let n=$('#moduleError');if(n){n.className='module-error';n.textContent=s}}
function dbError(e){renderMessage('Модули ещё не подключены',`Примените миграцию 20260907000000_focus_modules.sql в Supabase. ${e.message||''}`)}
window.addEventListener('focus-auth-change',()=>{lockVault();if(mode)render()});window.addEventListener('pagehide',lockVault);
['pointerdown','keydown'].forEach(type=>document.addEventListener(type,()=>{if(mode==='vault'&&vaultKey)armLock()},{passive:true}));
window.FocusModules={active:()=>!!mode,render,setMode};
})();
